### ISSUE TITLE
valid ftp links are registering as errors

### ISSUE THREAD

**Issue by nathanyoung** [CenturyLinkCloud/KB-Commit-Analyzer#1]
https://travis-ci.org/CenturyLinkCloud/PublicKB/builds/72219213#L262

The build log is displaying this valid ftp link as an error.

**Comment by thenickcox** [comment]
Good catch. Just fixed this and updated PublicKB with the new code.

### Edit

Also updated APIDocs and GettingStarted. To save you the headache, from now on, I'll respond to all bug reports in this repo by updating all three repos that depend on it unless you let me know other wise.

**Comment by thenickcox** [comment]
This commit worked locally, but it still found that ftp link on Travis. I'll make sure that it's running the correct version of the submodule.

**Comment by thenickcox** [comment]
It looks like the Travis builds are being concatenated together, so it appears that this is still an issue (if you search for `ftp` in the current build, it finds a match) but I don't believe that to be true.

The next commit to master on PublicKB should reset that; as for now, it looks like it's because the build had been restarted without a `git push`. So for now, I'll just keep an eye on it.

**Comment by nathanyoung** [comment]
:+1: PublicKB is now free of broken links!

**Comment by thenickcox** [comment]
Then it worked as intended! :tada:
